[www]
user = rawuser
group = www-data

listen = 9000

; Static: workers siempre vivos, sin overhead de spawn en cada request
pm = static
pm.max_children = 16
pm.max_requests = 500

; Logs de errores
php_admin_flag[log_errors] = on
